<?php
return [
    "ESTADO_INDEFINIDO" => 1,
    "ESTADO_PRESENTE" => 2,
    "ESTADO_FALTA" => 3,
    "ESTADO_CONGELADO" => 4,
    "ESTADO_LICENCIA" => 5,
    "ESTADO_FINALIZADO" => 6,
    "MOTIVO_LICENCIA_NIVELACION"=>1,
    "MOTIVO_LICENCIA_MATRICULACION"=>2
];